number1 = int(input("Please enter first number: "))
number2 = int(input("Please enter second number: "))
number3 = int(input("Please enter third number: "))
number4 = int(input("Please enter fourth number: "))
number5 = int(input("Please enter fifth number: "))
print(number1 + number2 + number3 + number4 + number5)
print(number1 / number2 / number3 / number4 / number5)
print(number1 * number2 * number3 * number4 * number5)
print(number1 - number2 - number3 - number4 - number5)
